// Word (.docx) exporter using `docx` package
//
// Usage:
//   const buffer = await toDOCX({ title, subtitle, columnsMeta, rows, summary, clinicName });
//   res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
//   res.setHeader('Content-Disposition', 'attachment; filename="report.docx"');
//   res.send(buffer);

const {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle, ShadingType,
} = require('docx');

async function toDOCX({ title = 'Report', subtitle = '', columnsMeta, rows, summary = {}, clinicName = '' }) {
  const children = [];

  // Header
  children.push(new Paragraph({
    alignment: AlignmentType.LEFT,
    children: [
      new TextRun({ text: 'SimpleRx EMR', bold: true, size: 28, color: '1565C0' }),
    ],
  }));
  if (clinicName) {
    children.push(new Paragraph({ children: [new TextRun({ text: clinicName, size: 20, color: '64748B' })] }));
  }
  children.push(new Paragraph({ text: '' }));

  // Title
  children.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text: title, bold: true, size: 32, color: '0D47A1' })],
  }));
  if (subtitle) {
    children.push(new Paragraph({ children: [new TextRun({ text: subtitle, italics: true, size: 18, color: '64748B' })] }));
  }
  children.push(new Paragraph({ text: '' }));

  // Summary section
  const summaryEntries = flattenSummary(summary);
  if (summaryEntries.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: 'Summary', bold: true, size: 24, color: '1565C0' })],
    }));
    const summaryTable = new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: summaryEntries.map(([k, v]) => new TableRow({
        children: [
          cell(k, { bold: true, bg: 'F0F7FF', width: 35 }),
          cell(formatVal(v), { width: 65 }),
        ],
      })),
    });
    children.push(summaryTable);
    children.push(new Paragraph({ text: '' }));
  }

  // Data table
  if (columnsMeta.length && rows.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: 'Data', bold: true, size: 24, color: '1565C0' })],
    }));

    const colWidth = Math.floor(100 / columnsMeta.length);
    const dataTable = new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        // Header row
        new TableRow({
          tableHeader: true,
          children: columnsMeta.map(c => cell(c.label, { bold: true, color: 'FFFFFF', bg: '1565C0', width: colWidth })),
        }),
        // Data rows
        ...rows.map((r, idx) => new TableRow({
          children: columnsMeta.map(c => cell(formatCell(r[c.key], c.type), {
            bg: idx % 2 === 1 ? 'F0F7FF' : undefined,
            width: colWidth,
          })),
        })),
      ],
    });
    children.push(dataTable);
  } else {
    children.push(new Paragraph({ children: [new TextRun({ text: 'No data for the selected filters.', italics: true, color: '64748B' })] }));
  }

  // Footer
  children.push(new Paragraph({ text: '' }));
  children.push(new Paragraph({
    children: [new TextRun({
      text: `Generated by SimpleRx EMR on ${new Date().toLocaleString('en-IN')}`,
      italics: true, size: 16, color: '64748B',
    })],
  }));

  const doc = new Document({
    creator: 'SimpleRx EMR',
    title,
    description: subtitle,
    sections: [{
      properties: { page: { margin: { top: 720, right: 720, bottom: 720, left: 720 } } },
      children,
    }],
  });

  return Packer.toBuffer(doc);
}

function cell(text, opts = {}) {
  const { bold, color, bg, width } = opts;
  return new TableCell({
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
    shading: bg ? { type: ShadingType.CLEAR, fill: bg } : undefined,
    margins: { top: 80, bottom: 80, left: 100, right: 100 },
    borders: {
      top:    { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
      bottom: { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
      left:   { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
      right:  { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
    },
    children: [new Paragraph({
      children: [new TextRun({ text: String(text ?? ''), bold: !!bold, color: color || '1F2937', size: 18 })],
    })],
  });
}

function formatCell(val, type) {
  if (val === null || val === undefined) return '';
  if (val instanceof Date) return val.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  if (type === 'currency') {
    const n = Number(val);
    return isNaN(n) ? String(val) : '\u20B9' + n.toLocaleString('en-IN', { maximumFractionDigits: 2 });
  }
  if (type === 'date' && typeof val === 'string') {
    const d = new Date(val);
    return isNaN(d) ? val : d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  }
  return String(val);
}

function formatVal(v) {
  if (v === null || v === undefined) return '';
  if (typeof v === 'number') return v.toLocaleString('en-IN');
  if (Array.isArray(v)) return v.map(x => Array.isArray(x) ? x.join(': ') : x).join('; ');
  if (typeof v === 'object') return Object.entries(v).map(([k, val]) => `${k}: ${val}`).join(', ');
  return String(v);
}

function flattenSummary(summary) {
  const out = [];
  for (const [k, v] of Object.entries(summary || {})) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      out.push([label(k), Object.entries(v).map(([k2, v2]) => `${k2}: ${v2}`).join(', ')]);
    } else if (Array.isArray(v)) {
      out.push([label(k), v.map(x => Array.isArray(x) ? x.join(' (') + ')' : x).join(', ')]);
    } else {
      out.push([label(k), v]);
    }
  }
  return out;
}

function label(k) {
  return k.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()).trim();
}

module.exports = { toDOCX };
